### ISSUE TITLE
Receiving exception BAD REQUEST

### ISSUE THREAD

**Issue by mayank-sol** [the-commons-project/CommonHealthClientSample#10]
Trying to run this Sample application on an emulator. I have already downloaded and configured the Common health developer edition application on same emulator.

But when launching the sample app, it crashes every time and in logs this error is got printed

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.thecommonsproject.android.commonhealth.sampleapp, PID: 7827
    org.thecommonsproject.android.common.interapp.InterappException$BadRequest
        at org.thecommonsproject.android.common.interapp.InterappErrorResponse$Companion.exceptionFromTypeAndMessage(InterappErrorResponse.kt:18)
        at org.thecommonsproject.android.common.interapp.InterappErrorResponse$Companion.fromBundle(InterappErrorResponse.kt:34)
        at org.thecommonsproject.android.common.interapp.BaseResponseReceiver.onReceiveResult(BaseResponseReceiver.kt:36)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7844)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Can anyone tell me the reason why this is happening?

I am developing the Health app and will integrated it with common health, if these things will work.

**Comment by mayank-sol** [comment]
I have found the cause, this is happening only on Android 12 (API 32) and above, it is working on lower android versions.
